- name: Demonstrate k8s modules
  hosts: localhost    
  gather_facts: no
  connection: local
  vars:
    namespace: emsya-dev 
  module_defaults:
    group/k8s:
      namespace: "{{ namespace }}"
      api_key: "sha256~3RemBFqGuYZ3v8SuqIsl5zSJxHYcfrMaH5SBiaugBWU"
      host: https://api.sandbox.x8i5.p1.openshiftapps.com:6443
  tasks:
    - name: Create objects from the manifest
      k8s:
        state: present
        src: "{{ playbook_dir + '/hello.yml' }}"


    - name: Change from ClusterIP to NodePort
      k8s_service:
        state: present
        name: nodejs-ex
        type: NodePort
        ports:
          - port: 8080
            protocol: TCP
  
